alert("JavaScript is working!");
const replies = [
"Potato approved! 🥔",
"The penguins voted yes. 🐧",
"I asked a duck. It said 'Quack.' 🦆",
"Fish knows the answer. 🐟",
"Only if the Moon says please. 🌙",
"A banana is currently investigating. 🍌",
"The cheese committee has rejected your request. 🧀",
"Beep boop! My brain is charging. 🤖",
"Error 404: Serious answer not found.",
"I accidentally ate the instruction manual.",
"The answer escaped on a skateboard.",
"My toaster refuses to comment.",
"A dinosaur stole the answer. 🦖",
"The potato council is still voting.",
"I rolled a dice. It landed on banana.",
"Your left sock knows everything.",
"Please consult the nearest rubber duck.",
"The answer is under your pillow.",
"I traded the answer for a cookie.",
"The unicorns are discussing it.",
"The answer is hiding behind a cactus.",
"I asked my fridge. It laughed.",
"The answer is spaghetti.",
"Only on Wednesdays.",
"Maybe yes. Maybe potato.",
"The answer smells like popcorn.",
"The Moon called. It said 'Perhaps.'",
"A squirrel is typing your answer.",
"I need exactly 17 marshmallows first.",
"My calculator is sleeping.",
"The clouds forgot.",
"The frogs are having a meeting.",
"The answer is invisible today.",
"A pirate stole my homework.",
"Your chair knows.",
"The answer went on holiday.",
"The banana has Wi-Fi now.",
"Penguins are surprisingly good lawyers.",
"I cannot answer until my hamster wakes up.",
"The answer is definitely purple.",
"An alien borrowed my brain.",
"I dropped the answer in soup.",
"The answer is allergic to Mondays.",
"My keyboard is laughing.",
"The ducks have unionised.",
"The potato became CEO.",
"The answer is loading... 2%",
"Try asking your ceiling fan.",
"The pancakes are plotting something.",
"The answer was eaten by a dragon.",
"I've misplaced reality.",
"The answer is dancing.",
"The spaghetti has spoken.",
"My socks are making important decisions.",
"A wizard turned the answer into jelly.",
"The answer is inside another answer.",
"I blinked and forgot.",
"The cheese whispered 'No.'",
"Congratulations! You unlocked Silly Mode.",
"Your question won an award for confusion.",
"I consulted an owl. It blinked twice.",
"The answer escaped through the window.",
"I tripped over a banana.",
"The answer is one pineapple tall.",
"I accidentally rebooted my potato.",
"The answer is underwater.",
"The answer has trust issues.",
"My shadow knows but won't tell me.",
"The answer is taking a nap.",
"Mission failed successfully.",
"The answer is behind the TV.",
"I've hidden it in Minecraft.",
"The answer is sponsored by ducks.",
"Beep! Brain overheating.",
"My banana battery is low.",
"The answer forgot its password.",
"A llama approved this message.",
"The jellybeans disagree.",
"The octopus pressed the wrong button.",
"I've never met a smarter potato.",
"The answer is 42... probably.",
"Please clap for the answer.",
"The answer is in another castle.",
"My goldfish said 'Absolutely.'",
"The answer is allergic to homework.",
"The unicorn ate my notes.",
"The answer is upside down.",
"I've outsourced thinking to squirrels.",
"The banana has become self-aware.",
"The answer is on airplane mode.",
"The dragon is still downloading.",
"The answer is hiding in the Wi-Fi.",
"The answer has gone shopping.",
"Even Google asked me.",
"The answer is busy eating pizza.",
"My sandwich has opinions.",
"The answer is chilling in Antarctica.",
"A cat unplugged my brain.",
"I only work on potato time.",
"The answer is a dancing carrot.",
"The cookie said maybe.",
"The answer has stage fright.",
"I'll answer after my nap... next year.",
"The answer is in stealth mode.",
"The Moon forgot.",
"The answer is orbiting Jupiter.",
"My pillow whispered the answer.",
"The ducks said 'Not today.'",
"I sneezed and lost the answer.",
"The answer became a meme.",
"The answer is hiding in your backpack.",
"The answer was confiscated by penguins.",
"My hamster is updating Windows.",
"The answer is encrypted in cheese.",
"The spaghetti committee is confused.",
"The answer is wearing sunglasses.",
"The answer escaped in a hot air balloon.",
"I accidentally mailed the answer to Mars.",
"The banana is buffering.",
"The potato is on holiday.",
"My spoon is judging me.",
"The answer is powered by rainbows.",
"I've reached maximum silliness.",
"The answer is too shiny.",
"The pancake flipped itself.",
"The answer is busy touching grass.",
"The answer joined a circus.",
"The answer slipped on soap.",
"The toaster became president.",
"The answer is chilling with Bigfoot.",
"The answer is in the lost and found.",
"My pet rock disagrees.",
"The answer is somewhere over the rainbow.",
"The answer is chewing bubblegum.",
"The answer forgot to set an alarm.",
"The answer is eating noodles.",
"I've asked three ducks already.",
"The answer is hiding in Area 51.",
"The answer was promoted to potato.",
"The answer is making coffee.",
"The answer is pretending to be serious.",
"The answer is currently invisible.",
"My shoes started arguing.",
"The answer won a dance competition.",
"The answer is in another dimension.",
"The answer is made of marshmallows.",
"I have achieved peak nonsense.",
"The answer is taking driving lessons.",
"The answer is busy watching cartoons.",
"The answer was kidnapped by squirrels.",
"The answer is charging at 1%.",
"The answer is allergic to gravity.",
"The answer is wearing a moustache.",
"My broccoli has Wi-Fi.",
"The answer is made of glitter.",
"The answer forgot English.",
"The answer is climbing a tree.",
"The answer is baking cookies.",
"The answer is playing hide-and-seek.",
"The answer is busy doing absolutely nothing.",
"The answer is somewhere between yes and potato.",
"The answer is classified by the Duck Agency.",
"The answer is impossible... unless you believe in bananas.",
"The answer is One piece is real",
"Vegeta is better than Goku"
];

function randomReply() {
    let index = Math.floor(Math.random() * replies.length);
    return replies[index];
}

function sendMessage() {

    let input = document.getElementById("userInput");
    let chat = document.getElementById("chat");

    let message = input.value;

    if (message.trim() === "") return;

    chat.innerHTML += `<div class="user"><b>You:</b> ${message}</div>`;

    chat.innerHTML += `<div class="bot"><b>Silly Bot:</b> ${randomReply()}</div>`;

    input.value = "";

    chat.scrollTop = chat.scrollHeight;
}